server:
  port: ${PORT:8082}

service:
  mock:
    base-url: https://jsonplaceholder.typicode.com
  todos:
    base-url: http://todos-service/
  kafka:
    base-url: http://127.0.0.1:9092

todos-service:
  todos-per-user: 10

spring:
  zipkin:
    base-url: http://localhost:9411/