spring:
  main:
    banner-mode: "off"
  zipkin:
    base-url: http://${SERVICE_LOCATION_ZIPKIN}

service:
  todos:
    base-url: http://${SERVICE_LOCATION_TODOS}
  kafka:
    base-url: http://${SERVICE_LOCATION_KAFKA}
