spring:
  main:
    banner-mode: "off"
  cloud:
    consul:
      host: ${SERVICE_HOST_CONSUL}
      port: ${SERVICE_HOST_CONSUL}

service:
  todos:
    base-url: http://${SERVICE_HOST_TODOS}:${SERVICE_PORT_TODOS}
  kafka:
    base-url: http://${SERVICE_HOST_KAFKA}:${SERVICE_PORT_KAFKA}